### ISSUE TITLE
Bracket Symmetry Tests Return Incorrect Results

### ISSUE THREAD

**Issue by zanderdenning** [TheRealMichaelWang/fastcode#3]
Function `block_checksum` returns true as long as the sum of all opening brackets, parenthesis, and braces equals the sum of all closing ones. They do not necessarily have to actually match for the function to return true.
For example:
```
1:[(
2:}
3:)
```
Returns true.

```
1:[{
2:)}}
```
Returns false, although it should raise an error. Adding `3:{` however causes it to return true.

**Comment by TheRealMichaelWang** [comment]
Changed `return brace_sum+ bracket_sum + paren_sum;` to `return brace_sum == bracket_sum == paren_sum == 0;`.
